import type { FieldConfig, FieldId } from "./types";

export const fieldConfigs: FieldConfig[] = [
  {
    id: "love",
    panelTitle: "What you love",
    lead: "What you",
    emphasis: "LOVE",
    prompt: "What experiences make you lose track of time?",
    inputPlaceholder: "Creating until I lose track of time",
    color: "#ab7dff",
    haloColor: "#76d8e6",
    orbitPosition: [0, 1.02, 0.04],
    orbitTilt: [0.34, -0.12],
    orbitProgress: 0.25,
    planetDeformationSeed: 0.7,
    focusCameraPosition: [-0.55, 0.18, 5.35],
    focusCameraTarget: [-0.55, 0.08, 0.32],
    nodeMotionProfile: { drift: 0.018, speed: 1, depth: 0.04 },
  },
  {
    id: "ability",
    panelTitle: "What you’re good at",
    lead: "What you’re",
    emphasis: "GOOD AT",
    prompt: "What do people repeatedly ask you for help with?",
    inputPlaceholder: "Making complex ideas feel clear",
    color: "#78a9ef",
    haloColor: "#8fc7ff",
    orbitPosition: [-1.02, 0, 0.1],
    orbitTilt: [0.22, 0.18],
    orbitProgress: 0.5,
    planetDeformationSeed: 2.1,
    focusCameraPosition: [-0.55, 0.18, 5.35],
    focusCameraTarget: [-0.55, 0.08, 0.32],
    nodeMotionProfile: { drift: 0.014, speed: 0.82, depth: 0.032 },
  },
  {
    id: "meaning",
    panelTitle: "What the world needs",
    lead: "What the",
    emphasis: "WORLD NEEDS",
    prompt: "Whose problems do you care enough to keep thinking about?",
    inputPlaceholder: "Helping people feel less lost",
    color: "#77cfb9",
    haloColor: "#75e7d5",
    orbitPosition: [1.02, 0, -0.08],
    orbitTilt: [-0.26, -0.16],
    orbitProgress: 0,
    planetDeformationSeed: 3.8,
    focusCameraPosition: [-0.55, 0.18, 5.35],
    focusCameraTarget: [-0.55, 0.08, 0.32],
    nodeMotionProfile: { drift: 0.021, speed: 0.68, depth: 0.05 },
  },
  {
    id: "paid",
    panelTitle: "What you can be paid for",
    lead: "What you can be",
    emphasis: "PAID FOR",
    prompt: "What kind of value could support the life you want?",
    inputPlaceholder: "Turning insight into useful work",
    color: "#d9a06f",
    haloColor: "#e99aae",
    orbitPosition: [0, -1.02, -0.02],
    orbitTilt: [-0.32, 0.14],
    orbitProgress: 0.75,
    planetDeformationSeed: 5.4,
    focusCameraPosition: [-0.55, 0.18, 5.35],
    focusCameraTarget: [-0.55, 0.08, 0.32],
    nodeMotionProfile: { drift: 0.012, speed: 0.58, depth: 0.028 },
  },
];

export const fieldsById = Object.fromEntries(fieldConfigs.map((field) => [field.id, field])) as Record<FieldId, FieldConfig>;
