import type { OntologyTheme } from "./types";

export const ontologyThemes = [
  { id: "creating", label: "Creating", dimensions: ["activity"], aliases: ["create", "creating", "make", "making", "craft", "invent"], chineseAliases: ["创造", "创作", "制作"], relatedThemeIds: ["building", "designing", "expression"] },
  { id: "building", parentId: "creating", label: "Building", dimensions: ["activity", "role"], aliases: ["build", "building", "built", "ship", "shipping", "prototype", "tool", "product", "useful things"], chineseAliases: ["搭建", "建设", "产品"], relatedThemeIds: ["execution", "access"] },
  { id: "designing", parentId: "creating", label: "Designing", dimensions: ["activity", "strength"], aliases: ["design", "designing", "interface", "ux", "visual", "experience", "shape", "aesthetic"], chineseAliases: ["设计", "界面", "体验"], relatedThemeIds: ["beauty", "clarity"] },
  { id: "expression", parentId: "creating", label: "Expression", dimensions: ["impact", "value"], aliases: ["express", "expression", "voice", "creative expression", "artistic", "self expression"], chineseAliases: ["表达", "自我表达"], relatedThemeIds: ["storytelling", "beauty"] },

  { id: "helping", label: "Helping", dimensions: ["activity", "impact"], aliases: ["help", "helping", "support", "supporting", "serve", "service", "useful", "care for"], chineseAliases: ["帮助", "支持", "服务"], relatedThemeIds: ["guidance", "wellbeing", "access"] },
  { id: "teaching", parentId: "helping", label: "Teaching", dimensions: ["activity", "role"], aliases: ["teach", "teaching", "teacher", "educate", "education", "train", "training", "class", "lesson"], chineseAliases: ["教学", "教育", "上课"], relatedThemeIds: ["learning", "explaining"] },
  { id: "mentoring", parentId: "helping", label: "Mentoring", dimensions: ["activity", "role"], aliases: ["mentor", "mentoring", "coach", "coaching", "guide", "guiding", "advise", "advice"], chineseAliases: ["指导", "辅导", "带人"], relatedThemeIds: ["guidance", "confidence"] },
  { id: "caring", parentId: "helping", label: "Caring", dimensions: ["value", "impact"], aliases: ["care", "caring", "kindness", "nurture", "protect", "healing", "wellbeing"], chineseAliases: ["关心", "照顾", "疗愈"], relatedThemeIds: ["wellbeing", "empathy"] },

  { id: "understanding", label: "Understanding", dimensions: ["activity", "strength"], aliases: ["understand", "understanding", "make sense", "insight", "pattern", "patterns", "learn why"], chineseAliases: ["理解", "洞察", "看懂"], relatedThemeIds: ["researching", "analysis", "clarity"] },
  { id: "researching", parentId: "understanding", label: "Researching", dimensions: ["activity"], aliases: ["research", "researching", "study", "studying", "investigate", "investigating", "deep dive"], chineseAliases: ["研究", "调研", "调查"], relatedThemeIds: ["curiosity", "analysis"] },
  { id: "analysis", parentId: "understanding", label: "Analysis", dimensions: ["activity", "strength"], aliases: ["analyze", "analysis", "analytical", "data", "model", "evaluate", "diagnose"], chineseAliases: ["分析", "数据", "判断"], relatedThemeIds: ["better-decisions", "strategy"] },
  { id: "synthesis", parentId: "understanding", label: "Synthesis", dimensions: ["strength", "role"], aliases: ["synthesize", "synthesis", "connect dots", "big picture", "summarize", "distill"], chineseAliases: ["整合", "总结", "提炼"], relatedThemeIds: ["clarity", "translator"] },

  { id: "communicating", label: "Communicating", dimensions: ["activity", "strength"], aliases: ["communicate", "communication", "share", "present", "speak", "speaking", "write", "writing"], chineseAliases: ["沟通", "表达", "写作"], relatedThemeIds: ["explaining", "storytelling", "clarity"] },
  { id: "explaining", parentId: "communicating", label: "Explaining", dimensions: ["activity", "strength", "role"], aliases: ["explain", "explaining", "clarify", "make clear", "break down", "translate complex"], chineseAliases: ["解释", "讲清楚", "说明"], relatedThemeIds: ["clarity", "translator"] },
  { id: "storytelling", parentId: "communicating", label: "Storytelling", dimensions: ["activity", "strength"], aliases: ["story", "stories", "storytelling", "narrative", "tell stories", "content"], chineseAliases: ["讲故事", "叙事", "内容"], relatedThemeIds: ["belonging", "expression"] },
  { id: "persuading", parentId: "communicating", label: "Persuading", dimensions: ["activity", "strength"], aliases: ["persuade", "persuading", "pitch", "sell", "influence", "convince"], chineseAliases: ["说服", "影响", "销售"], relatedThemeIds: ["confidence", "leadership"] },

  { id: "connecting", label: "Connecting", dimensions: ["activity", "value", "impact"], aliases: ["connect", "connecting", "relationship", "network", "community", "bring together"], chineseAliases: ["连接", "关系", "社群"], relatedThemeIds: ["belonging", "teams", "community"] },
  { id: "collaboration", parentId: "connecting", label: "Collaboration", dimensions: ["workStyle", "value"], aliases: ["collaborate", "collaboration", "together", "teamwork", "co-create"], chineseAliases: ["合作", "协作", "一起"], relatedThemeIds: ["teams", "belonging"] },
  { id: "community", parentId: "connecting", label: "Community", dimensions: ["audience", "impact"], aliases: ["community", "communities", "local community", "belong", "gather"], chineseAliases: ["社区", "社群", "归属"], relatedThemeIds: ["belonging", "local-communities"] },
  { id: "relationship-building", parentId: "connecting", label: "Relationship building", dimensions: ["strength"], aliases: ["relationship building", "relationships", "trust", "rapport", "people know"], chineseAliases: ["建立关系", "信任"], relatedThemeIds: ["empathy", "people-facing"] },

  { id: "leading", label: "Leading", dimensions: ["activity", "role"], aliases: ["lead", "leading", "leader", "leadership", "own", "ownership", "direct"], chineseAliases: ["领导", "带领", "负责"], relatedThemeIds: ["strategy", "organizing"] },
  { id: "strategy", parentId: "leading", label: "Strategy", dimensions: ["strength", "workStyle", "role"], aliases: ["strategy", "strategic", "roadmap", "vision", "prioritize", "direction"], chineseAliases: ["战略", "策略", "方向"], relatedThemeIds: ["better-decisions", "organizing"] },
  { id: "judgment", parentId: "leading", label: "Judgment", dimensions: ["strength"], aliases: ["judgment", "discern", "taste", "decision", "decide", "good call"], chineseAliases: ["判断", "决策", "品味"], relatedThemeIds: ["better-decisions", "clarity"] },
  { id: "advocacy", parentId: "leading", label: "Advocacy", dimensions: ["role", "impact"], aliases: ["advocate", "advocacy", "speak up", "justice", "fair", "fairness"], chineseAliases: ["倡导", "公平", "发声"], relatedThemeIds: ["fairness", "access"] },

  { id: "organizing", label: "Organizing", dimensions: ["activity", "strength"], aliases: ["organize", "organizing", "plan", "planning", "structure", "system", "process"], chineseAliases: ["组织", "规划", "系统"], relatedThemeIds: ["structured", "operating", "efficiency"] },
  { id: "operating", parentId: "organizing", label: "Operating", dimensions: ["activity", "role"], aliases: ["operate", "operating", "run", "manage", "ops", "logistics", "execute"], chineseAliases: ["运营", "执行", "管理"], relatedThemeIds: ["execution", "efficiency"] },
  { id: "attention-detail", parentId: "organizing", label: "Attention to detail", dimensions: ["strength"], aliases: ["detail", "details", "precise", "precision", "careful", "polish"], chineseAliases: ["细节", "精确", "严谨"], relatedThemeIds: ["mastery", "quality"] },
  { id: "execution", parentId: "organizing", label: "Execution", dimensions: ["strength", "workStyle"], aliases: ["execution", "execute", "finish", "deliver", "ship", "make happen"], chineseAliases: ["执行", "落地", "完成"], relatedThemeIds: ["building", "operating"] },

  { id: "exploring", label: "Exploring", dimensions: ["activity", "value"], aliases: ["explore", "exploring", "discover", "try new", "experiment", "wander", "travel"], chineseAliases: ["探索", "发现", "尝试"], relatedThemeIds: ["curiosity", "adventure", "flexible"] },
  { id: "curiosity", parentId: "exploring", label: "Curiosity", dimensions: ["value", "strength"], aliases: ["curious", "curiosity", "questions", "wonder", "learn", "learning"], chineseAliases: ["好奇", "求知", "学习"], relatedThemeIds: ["researching", "growth"] },
  { id: "adaptability", parentId: "exploring", label: "Adaptability", dimensions: ["strength", "workStyle"], aliases: ["adapt", "adaptable", "flexible", "change", "uncertain", "ambiguity"], chineseAliases: ["适应", "灵活", "变化"], relatedThemeIds: ["flexible", "adventure"] },
  { id: "adventure", parentId: "exploring", label: "Adventure", dimensions: ["value"], aliases: ["adventure", "novelty", "new places", "risk", "bold"], chineseAliases: ["冒险", "新鲜", "大胆"], relatedThemeIds: ["freedom", "exploring"] },

  { id: "problem-solving", label: "Problem solving", dimensions: ["activity", "strength"], aliases: ["solve", "solving", "problem", "problem solving", "fix", "troubleshoot"], chineseAliases: ["解决问题", "修复"], relatedThemeIds: ["analysis", "building"] },
  { id: "better-decisions", parentId: "problem-solving", label: "Better decisions", dimensions: ["impact"], aliases: ["better decisions", "decide better", "choice", "prioritize", "less confused"], chineseAliases: ["更好决策", "选择"], relatedThemeIds: ["clarity", "judgment"] },
  { id: "efficiency", parentId: "problem-solving", label: "Efficiency", dimensions: ["impact"], aliases: ["efficiency", "efficient", "faster", "save time", "streamline", "simplify"], chineseAliases: ["效率", "省时间", "简化"], relatedThemeIds: ["operating", "organizing"] },
  { id: "access", parentId: "problem-solving", label: "Access", dimensions: ["impact", "value"], aliases: ["access", "accessible", "open up", "available", "lower barrier"], chineseAliases: ["可及", "门槛", "获得"], relatedThemeIds: ["fairness", "underserved"] },

  { id: "empathy", label: "Empathy", dimensions: ["strength", "value"], aliases: ["empathy", "empathetic", "listen", "listening", "feel with", "understand people"], chineseAliases: ["共情", "倾听", "理解人"], relatedThemeIds: ["caring", "guidance"] },
  { id: "guidance", parentId: "empathy", label: "Guidance", dimensions: ["impact", "role"], aliases: ["guidance", "guide", "help navigate", "direction", "support through"], chineseAliases: ["引导", "指引"], relatedThemeIds: ["mentoring", "confidence"] },
  { id: "confidence", parentId: "empathy", label: "Confidence", dimensions: ["impact"], aliases: ["confidence", "confident", "encourage", "reassure", "less afraid"], chineseAliases: ["自信", "鼓励", "安心"], relatedThemeIds: ["guidance", "teaching"] },
  { id: "wellbeing", parentId: "empathy", label: "Well-being", dimensions: ["impact", "value"], aliases: ["wellbeing", "well-being", "healthy", "calm", "safe", "mental health"], chineseAliases: ["身心健康", "安心", "平静"], relatedThemeIds: ["caring", "stability"] },

  { id: "beauty", label: "Beauty", dimensions: ["value", "impact"], aliases: ["beauty", "beautiful", "aesthetic", "elegant", "taste", "craft"], chineseAliases: ["美", "审美", "优雅"], relatedThemeIds: ["designing", "quality"] },
  { id: "mastery", label: "Mastery", dimensions: ["value", "workStyle"], aliases: ["mastery", "skill", "craft", "practice", "excellent", "expert"], chineseAliases: ["精通", "手艺", "专业"], relatedThemeIds: ["attention-detail", "quality"] },
  { id: "growth", label: "Growth", dimensions: ["value"], aliases: ["growth", "grow", "improve", "develop", "learn", "become better"], chineseAliases: ["成长", "进步"], relatedThemeIds: ["curiosity", "learning"] },
  { id: "freedom", label: "Freedom", dimensions: ["value", "workStyle"], aliases: ["freedom", "free", "autonomy", "independent", "own schedule"], chineseAliases: ["自由", "自主"], relatedThemeIds: ["independent", "flexible"] },
  { id: "stability", label: "Stability", dimensions: ["value"], aliases: ["stability", "stable", "security", "secure", "steady", "reliable"], chineseAliases: ["稳定", "安全感"], relatedThemeIds: ["structured", "security"] },
  { id: "recognition", label: "Recognition", dimensions: ["value"], aliases: ["recognition", "recognized", "seen", "appreciated", "status"], chineseAliases: ["认可", "看见", "成就感"], relatedThemeIds: ["confidence"] },
  { id: "belonging", label: "Belonging", dimensions: ["value", "impact"], aliases: ["belonging", "belong", "included", "inclusion", "home", "together"], chineseAliases: ["归属", "包容"], relatedThemeIds: ["community", "connecting"] },
  { id: "fairness", label: "Fairness", dimensions: ["value", "impact"], aliases: ["fair", "fairness", "justice", "equity", "equal", "ethical"], chineseAliases: ["公平", "正义"], relatedThemeIds: ["advocacy", "access"] },
  { id: "security", parentId: "stability", label: "Security", dimensions: ["value"], aliases: ["security", "safe", "safety", "financial security", "reliable income"], chineseAliases: ["安全", "保障"], relatedThemeIds: ["stability", "paid"] },

  { id: "clarity", label: "Clarity", dimensions: ["impact"], aliases: ["clarity", "clear", "make clear", "less confusion", "understand better"], chineseAliases: ["清晰", "清楚"], relatedThemeIds: ["explaining", "synthesis"] },
  { id: "learning", label: "Learning", dimensions: ["impact", "value"], aliases: ["learning", "learn", "teach someone", "knowledge", "skill building"], chineseAliases: ["学习", "知识"], relatedThemeIds: ["teaching", "growth"] },
  { id: "opportunity", label: "Opportunity", dimensions: ["impact"], aliases: ["opportunity", "chance", "open doors", "career", "mobility"], chineseAliases: ["机会", "发展"], relatedThemeIds: ["access", "growth"] },
  { id: "connection", label: "Connection", dimensions: ["impact"], aliases: ["connection", "connected", "less alone", "relationships", "bridge"], chineseAliases: ["连接感", "关系"], relatedThemeIds: ["connecting", "belonging"] },
  { id: "positive-change", label: "Positive change", dimensions: ["impact"], aliases: ["change", "positive change", "impact", "better world", "improve lives"], chineseAliases: ["改变", "影响", "变好"], relatedThemeIds: ["service", "fairness"] },

  { id: "students", label: "Students", dimensions: ["audience"], aliases: ["students", "student", "learners", "classmates", "kids in school"], chineseAliases: ["学生", "学习者"], relatedThemeIds: ["teaching", "learning"] },
  { id: "young-people", label: "Young people", dimensions: ["audience"], aliases: ["young people", "youth", "kids", "children", "teens"], chineseAliases: ["年轻人", "孩子", "青少年"], relatedThemeIds: ["teaching", "guidance"] },
  { id: "founders", label: "Founders", dimensions: ["audience"], aliases: ["founders", "startup", "entrepreneurs", "builders", "small business"], chineseAliases: ["创业者", "创始人"], relatedThemeIds: ["strategy", "building"] },
  { id: "creators", label: "Creators", dimensions: ["audience"], aliases: ["creators", "artists", "writers", "designers", "makers"], chineseAliases: ["创作者", "设计师"], relatedThemeIds: ["creating", "expression"] },
  { id: "professionals", label: "Professionals", dimensions: ["audience"], aliases: ["professionals", "workers", "clients", "customers", "operators"], chineseAliases: ["职场人", "客户"], relatedThemeIds: ["clarity", "efficiency"] },
  { id: "teams", label: "Teams", dimensions: ["audience"], aliases: ["teams", "team", "coworkers", "colleagues", "organizations"], chineseAliases: ["团队", "同事", "组织"], relatedThemeIds: ["collaboration", "organizing"] },
  { id: "families", label: "Families", dimensions: ["audience"], aliases: ["families", "family", "parents", "caregivers"], chineseAliases: ["家庭", "父母", "家人"], relatedThemeIds: ["caring", "wellbeing"] },
  { id: "local-communities", label: "Local communities", dimensions: ["audience"], aliases: ["local community", "neighborhood", "city", "local people"], chineseAliases: ["本地社区", "社区"], relatedThemeIds: ["community", "access"] },
  { id: "underserved", label: "Underserved groups", dimensions: ["audience"], aliases: ["underserved", "marginalized", "low income", "people without access"], chineseAliases: ["弱势群体", "资源不足"], relatedThemeIds: ["fairness", "access"] },
  { id: "consumers", label: "Consumers", dimensions: ["audience"], aliases: ["consumers", "users", "customers", "buyers", "people using"], chineseAliases: ["用户", "消费者"], relatedThemeIds: ["designing", "access"] },

  { id: "independent", label: "Independent work", dimensions: ["workStyle"], aliases: ["independent", "alone", "solo", "deep work", "self directed"], chineseAliases: ["独立", "自己做"], relatedThemeIds: ["freedom", "behind-scenes"] },
  { id: "hands-on", label: "Hands-on work", dimensions: ["workStyle"], aliases: ["hands on", "hands-on", "practical", "tangible", "making things"], chineseAliases: ["动手", "实践"], relatedThemeIds: ["building", "execution"] },
  { id: "fast-paced", label: "Fast-paced work", dimensions: ["workStyle"], aliases: ["fast paced", "fast-paced", "urgent", "quick", "rapid"], chineseAliases: ["快节奏", "快速"], relatedThemeIds: ["execution", "adaptability"] },
  { id: "structured", label: "Structured work", dimensions: ["workStyle"], aliases: ["structured", "clear process", "routine", "organized", "predictable"], chineseAliases: ["结构化", "有序"], relatedThemeIds: ["organizing", "stability"] },
  { id: "flexible", label: "Flexible work", dimensions: ["workStyle"], aliases: ["flexible", "fluid", "open ended", "variety", "varied"], chineseAliases: ["灵活", "开放"], relatedThemeIds: ["freedom", "adaptability"] },
  { id: "people-facing", label: "People-facing work", dimensions: ["workStyle"], aliases: ["people facing", "client facing", "with people", "facilitate", "workshop"], chineseAliases: ["面对人", "客户沟通"], relatedThemeIds: ["communication", "relationship-building"] },
  { id: "behind-scenes", label: "Behind-the-scenes work", dimensions: ["workStyle"], aliases: ["behind the scenes", "backstage", "quiet work", "systems work"], chineseAliases: ["幕后", "安静工作"], relatedThemeIds: ["independent", "operating"] },
  { id: "entrepreneurial", label: "Entrepreneurial work", dimensions: ["workStyle"], aliases: ["entrepreneurial", "startup", "ownership", "self starter", "venture"], chineseAliases: ["创业", "自主负责"], relatedThemeIds: ["founders", "leading"] },

  { id: "nature-environment", label: "Nature and environment", dimensions: ["value", "impact"], aliases: ["nature", "environment", "environmental", "climate", "ecosystem", "sustainability", "conservation", "planet"], chineseAliases: ["自然", "环境", "气候", "环保", "可持续"], relatedThemeIds: ["positive-change"] },
  { id: "food-hospitality", label: "Food and hospitality", dimensions: ["activity", "value", "impact"], aliases: ["cook", "cooking", "food", "meal", "dining", "hospitality", "hosting", "baking"], chineseAliases: ["烹饪", "做饭", "食物", "餐饮", "待客"], relatedThemeIds: ["connection", "caring", "craftsmanship"] },
  { id: "movement-health", label: "Movement and health", dimensions: ["activity", "value", "impact"], aliases: ["fitness", "exercise", "workout", "movement", "athletics", "sport", "running", "strength training"], chineseAliases: ["健身", "运动", "锻炼", "健康"], relatedThemeIds: ["wellbeing", "disciplined-practice"] },
  { id: "artistic-performance", parentId: "creating", label: "Artistic performance", dimensions: ["activity", "value"], aliases: ["music", "musician", "piano", "perform", "performance", "concert", "composition", "dance", "theater"], chineseAliases: ["音乐", "钢琴", "表演", "演出", "舞蹈"], relatedThemeIds: ["expression", "creative-thinking"] },
  { id: "craftsmanship", parentId: "creating", label: "Craftsmanship", dimensions: ["activity", "strength", "value"], aliases: ["craftsmanship", "woodworking", "furniture", "ceramics", "sewing", "repair", "restoration", "made by hand"], chineseAliases: ["手工", "木工", "修复", "工艺"], relatedThemeIds: ["hands-on", "mastery", "attention-detail"] },
  { id: "facilitation", parentId: "communicating", label: "Facilitation", dimensions: ["activity", "strength", "role"], aliases: ["facilitate", "facilitation", "moderate", "mediation", "group discussion", "build consensus", "workshop facilitator"], chineseAliases: ["引导讨论", "主持", "协调讨论", "共识"], relatedThemeIds: ["collaboration", "better-decisions", "people-facing"] },
  { id: "quantitative-reasoning", parentId: "understanding", label: "Quantitative reasoning", dimensions: ["strength"], aliases: ["quantitative", "mathematical", "math", "numbers", "calculate", "calculation", "statistics", "probability", "numerical"], chineseAliases: ["数学", "数字", "计算", "统计", "概率", "量化"], relatedThemeIds: ["analysis", "pattern-recognition"] },
  { id: "creative-thinking", parentId: "creating", label: "Creative thinking", dimensions: ["strength"], aliases: ["creative", "creativity", "imagination", "imaginative", "ideation", "original ideas"], chineseAliases: ["创意", "创造力", "想象力"], relatedThemeIds: ["expression", "designing", "artistic-performance"] },
  { id: "pattern-recognition", parentId: "understanding", label: "Pattern recognition", dimensions: ["strength"], aliases: ["pattern recognition", "spot patterns", "recognize patterns", "see trends", "connect signals"], chineseAliases: ["模式识别", "发现规律", "看趋势"], relatedThemeIds: ["analysis", "synthesis", "quantitative-reasoning"] },
  { id: "systems-thinking", parentId: "understanding", label: "Systems thinking", dimensions: ["strength"], aliases: ["systems thinking", "systems thinker", "system design", "understand systems", "architecture", "dependencies"], chineseAliases: ["系统思维", "系统设计", "架构"], relatedThemeIds: ["analysis", "organizing", "problem-solving"] },
  { id: "spatial-thinking", label: "Spatial thinking", dimensions: ["strength"], aliases: ["spatial", "three dimensional", "3d", "visualize space", "spatial reasoning"], chineseAliases: ["空间思维", "三维", "空间感"], relatedThemeIds: ["designing", "craftsmanship"] },
  { id: "social-perception", parentId: "empathy", label: "Social perception", dimensions: ["strength"], aliases: ["read people", "social perception", "read the room", "notice emotions", "understand motivations"], chineseAliases: ["察言观色", "理解他人", "看懂人"], relatedThemeIds: ["empathy", "relationship-building"] },
  { id: "disciplined-practice", parentId: "mastery", label: "Disciplined practice", dimensions: ["strength", "workStyle"], aliases: ["disciplined practice", "practice daily", "rehearse", "repetition", "consistent practice"], chineseAliases: ["刻意练习", "坚持练习", "长期训练"], relatedThemeIds: ["mastery", "attention-detail"] },

  { id: "builder-role", label: "Builder", dimensions: ["role"], aliases: ["builder", "maker", "product person", "creator"], chineseAliases: ["搭建者", "创造者"], relatedThemeIds: ["building", "creating", "execution"] },
  { id: "guide-role", label: "Guide", dimensions: ["role"], aliases: ["guide", "coach", "mentor", "advisor"], chineseAliases: ["引导者", "导师"], relatedThemeIds: ["mentoring", "guidance", "empathy"] },
  { id: "translator", label: "Translator", dimensions: ["role"], aliases: ["translator", "translate", "bridge", "make complex simple"], chineseAliases: ["翻译者", "桥梁"], relatedThemeIds: ["explaining", "synthesis", "clarity"] },
  { id: "connector-role", label: "Connector", dimensions: ["role"], aliases: ["connector", "community builder", "networker", "bring people together"], chineseAliases: ["连接者"], relatedThemeIds: ["connecting", "community", "relationship-building"] },
  { id: "investigator", label: "Investigator", dimensions: ["role"], aliases: ["investigator", "researcher", "detective", "analyst"], chineseAliases: ["研究者", "调查者"], relatedThemeIds: ["researching", "analysis", "curiosity"] },
  { id: "organizer-role", label: "Organizer", dimensions: ["role"], aliases: ["organizer", "planner", "operator", "coordinator"], chineseAliases: ["组织者", "协调者"], relatedThemeIds: ["organizing", "operating"] },
  { id: "storyteller-role", label: "Storyteller", dimensions: ["role"], aliases: ["storyteller", "writer", "narrator", "content creator"], chineseAliases: ["讲述者", "内容创作者"], relatedThemeIds: ["storytelling", "expression"] },
  { id: "strategist-role", label: "Strategist", dimensions: ["role"], aliases: ["strategist", "planner", "advisor", "decision partner"], chineseAliases: ["策略师", "规划者"], relatedThemeIds: ["strategy", "judgment", "better-decisions"] },
] satisfies OntologyTheme[];

export const ontologyById = Object.fromEntries(ontologyThemes.map((theme) => [theme.id, theme])) as Record<string, OntologyTheme>;

export const parentThemes = ontologyThemes.filter((theme) => !theme.parentId);
export const childThemes = ontologyThemes.filter((theme) => theme.parentId);
